import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import navLogo from "@/assets/nav-logo.png";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "400", "600", "700"],
});

export const roboto = Roboto({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "News Portal",
  description: "Generated by create next app",

  icons: {
    icon: navLogo.src,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${poppins.className} min-h-screen flex flex-col`}>
        {children}
      </body>
    </html>
  );
}